version: '3'

services:
  mongodb:
    image: tutum/mongodb
    environment:
      - AUTH=no
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - techturbid-bridge

#  terraform:
#    build: ./terraform
#    environment:
#    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
#    - AWS_REGION=${AWS_DEFAULT_REGION}
#    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
#    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
#    networks:
#      - techturbid-bridge

  api:
    build: ./src/api
    environment:
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - AWS_REGION=${AWS_DEFAULT_REGION}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8123:8123"
    expose:
      - "8123"
    networks:
      - techturbid-bridge

  worker:
    build: ./src/worker
    depends_on:
      - mongodb
    networks:
      - techturbid-bridge

networks:
  techturbid-bridge:
    driver: bridge
